"""
STENO Transpiler
Converts the AST to valid Python source code.
Used by `steno compile` to produce a .py file.
"""

from typing import List, Optional
import ast_nodes as N


class TranspileError(Exception):
    def __init__(self, msg: str, line: int = 0):
        super().__init__(f"TranspileError at line {line}: {msg}")


class Transpiler:
    def __init__(self):
        self.indent_level = 0
        self.lines: List[str] = []

    def _i(self) -> str:
        return "    " * self.indent_level

    def emit(self, text: str):
        self.lines.append(self._i() + text)

    def output(self) -> str:
        return "\n".join(self.lines)

    def transpile(self, node: N.Program) -> str:
        self.lines = [
            "# Generated by STENO transpiler — do not edit directly.",
            "# Source: .sten file\n"
        ]
        for s in node.body:
            self._stmt(s)
        return self.output()

    # ── Statements ────────────────────────────────────────────────────────────

    def _stmt(self, node: N.Node):
        m = getattr(self, f"_s_{type(node).__name__}", None)
        if m is None:
            raise TranspileError(f"No transpiler for '{type(node).__name__}'")
        m(node)

    def _block(self, stmts: List[N.Node]):
        self.indent_level += 1
        if not stmts:
            self.emit("pass")
        else:
            for s in stmts:
                self._stmt(s)
        self.indent_level -= 1

    def _s_ExprStmt(self,    n): self.emit(self._e(n.expr))
    def _s_PassStmt(self,    n): self.emit("pass")
    def _s_BreakStmt(self,   n): self.emit("break")
    def _s_ContinueStmt(self,n): self.emit("continue")

    def _s_VarDecl(self, n: N.VarDecl):
        v = f" = {self._e(n.value)}" if n.value is not None else " = None"
        self.emit(f"{n.name}{v}")

    def _s_Assign(self, n: N.Assign):
        self.emit(f"{self._e(n.target)} {n.op} {self._e(n.value)}")

    def _s_PrintStmt(self, n: N.PrintStmt):
        args = ", ".join(self._e(a) for a in n.args)
        self.emit(f"print({args})")

    def _s_ReturnStmt(self, n: N.ReturnStmt):
        self.emit(f"return {self._e(n.value)}" if n.value else "return")

    def _s_YieldStmt(self, n: N.YieldStmt):
        self.emit(f"yield {self._e(n.value)}" if n.value else "yield")

    def _s_DelStmt(self,      n): self.emit(f"del {self._e(n.target)}")
    def _s_GlobalStmt(self,   n): self.emit(f"global {', '.join(n.names)}")
    def _s_NonlocalStmt(self, n): self.emit(f"nonlocal {', '.join(n.names)}")
    def _s_AssertStmt(self,   n):
        s = f"assert {self._e(n.test)}"
        if n.msg: s += f", {self._e(n.msg)}"
        self.emit(s)

    def _s_ImportStmt(self, n: N.ImportStmt):
        if n.names:
            self.emit(f"from {n.module} import {', '.join(n.names)}")
        elif n.alias:
            self.emit(f"import {n.module} as {n.alias}")
        else:
            self.emit(f"import {n.module}")

    def _s_FuncDef(self, n: N.FuncDef):
        params = []
        for p in n.params:
            params.append(f"{p}={self._e(n.defaults[p])}"
                          if p in n.defaults else p)
        for d in n.decorators:
            self.emit(f"@{self._e(d)}")
        self.emit(f"def {n.name}({', '.join(params)}):")
        self._block(n.body)

    def _s_ClassDef(self, n: N.ClassDef):
        bases = f"({', '.join(self._e(b) for b in n.bases)})" if n.bases else ""
        self.emit(f"class {n.name}{bases}:")
        self._block(n.body)

    def _s_IfStmt(self, n: N.IfStmt):
        self.emit(f"if {self._e(n.condition)}:")
        self._block(n.then_body)
        for cond, body in n.elif_clauses:
            self.emit(f"elif {self._e(cond)}:")
            self._block(body)
        if n.else_body is not None:
            self.emit("else:")
            self._block(n.else_body)

    def _s_ForLoop(self, n: N.ForLoop):
        start = self._e(n.start); stop = self._e(n.stop)
        rng   = (f"range({start}, {stop}, {self._e(n.step)})"
                 if n.step else f"range({start}, {stop})")
        self.emit(f"for {n.var} in {rng}:")
        self._block(n.body)

    def _s_ForInLoop(self, n: N.ForInLoop):
        self.emit(f"for {n.var} in {self._e(n.iterable)}:")
        self._block(n.body)

    def _s_WhileLoop(self, n: N.WhileLoop):
        self.emit(f"while {self._e(n.condition)}:")
        self._block(n.body)

    def _s_TryStmt(self, n: N.TryStmt):
        self.emit("try:")
        self._block(n.body)
        for exc_type, exc_name, body in n.handlers:
            if exc_type and exc_name: self.emit(f"except {self._e(exc_type)} as {exc_name}:")
            elif exc_type:            self.emit(f"except {self._e(exc_type)}:")
            else:                     self.emit("except:")
            self._block(body)
        if n.else_body:
            self.emit("else:"); self._block(n.else_body)
        if n.finally_body:
            self.emit("finally:"); self._block(n.finally_body)

    def _s_WithStmt(self, n: N.WithStmt):
        s = f"with {self._e(n.context)}"
        if n.alias: s += f" as {n.alias}"
        self.emit(s + ":")
        self._block(n.body)

    # ── Expressions ───────────────────────────────────────────────────────────

    def _e(self, node) -> str:
        if node is None: return "None"
        m = getattr(self, f"_x_{type(node).__name__}", None)
        if m is None:
            raise TranspileError(f"No transpiler for expr '{type(node).__name__}'")
        return m(node)

    def _x_IntLit(self,   n): return str(n.value)
    def _x_FloatLit(self, n): return str(n.value)
    def _x_StrLit(self,   n): return repr(n.value)
    def _x_BoolLit(self,  n): return "True" if n.value else "False"
    def _x_NoneLit(self,  n): return "None"
    def _x_Name(self,     n): return n.name

    def _x_BinOp(self, n: N.BinOp) -> str:
        l = self._maybe_paren(n.left);  r = self._maybe_paren(n.right)
        return f"{l} {n.op} {r}"

    def _maybe_paren(self, node) -> str:
        s = self._e(node)
        return f"({s})" if isinstance(node, (N.BoolOp, N.Ternary)) else s

    def _x_UnaryOp(self, n: N.UnaryOp) -> str:
        v = self._e(n.operand)
        return f"not {v}" if n.op == "not" else f"{n.op}{v}"

    def _x_Compare(self, n: N.Compare) -> str:
        parts = [self._e(n.left)]
        for op, c in zip(n.ops, n.comparators):
            parts += [op, self._e(c)]
        return " ".join(parts)

    def _x_BoolOp(self, n: N.BoolOp) -> str:
        sep = f" {n.op} "
        return sep.join(
            f"({self._e(v)})" if isinstance(v, N.BoolOp) else self._e(v)
            for v in n.values)

    def _x_Call(self, n: N.Call) -> str:
        args   = [self._e(a) for a in n.args]
        kwargs = [f"{k}={self._e(v)}" for k, v in n.kwargs]
        return f"{self._e(n.func)}({', '.join(args + kwargs)})"

    def _x_Index(self, n: N.Index) -> str:
        return f"{self._e(n.obj)}[{self._e(n.index)}]"

    def _x_Slice(self, n: N.Slice) -> str:
        lo = self._e(n.lower) if n.lower else ""
        hi = self._e(n.upper) if n.upper else ""
        st = f":{self._e(n.step)}" if n.step else ""
        return f"{self._e(n.obj)}[{lo}:{hi}{st}]"

    def _x_Attr(self, n: N.Attr) -> str:
        return f"{self._e(n.obj)}.{n.attr}"

    def _x_ListLit(self,  n): return "[" + ", ".join(self._e(e) for e in n.elements) + "]"
    def _x_DictLit(self,  n): return "{" + ", ".join(f"{self._e(k)}: {self._e(v)}" for k,v in n.pairs) + "}"
    def _x_SetLit(self,   n): return "{" + ", ".join(self._e(e) for e in n.elements) + "}"
    def _x_TupleLit(self, n):
        if not n.elements: return "()"
        if len(n.elements) == 1: return f"({self._e(n.elements[0])},)"
        return "(" + ", ".join(self._e(e) for e in n.elements) + ")"

    def _x_ListComp(self, n: N.ListComp) -> str:
        cond = f" if {self._e(n.condition)}" if n.condition else ""
        return f"[{self._e(n.expr)} for {n.var} in {self._e(n.iterable)}{cond}]"

    def _x_DictComp(self, n: N.DictComp) -> str:
        cond = f" if {self._e(n.condition)}" if n.condition else ""
        return (f"{{{self._e(n.key_expr)}: {self._e(n.val_expr)}"
                f" for {n.var} in {self._e(n.iterable)}{cond}}}")

    def _x_Lambda(self, n: N.Lambda) -> str:
        return f"lambda {', '.join(n.params)}: {self._e(n.body)}"

    def _x_Ternary(self, n: N.Ternary) -> str:
        return (f"{self._e(n.then_expr)} if {self._e(n.condition)}"
                f" else {self._e(n.else_expr)}")
